apiVersion: v1
kind: Service
metadata:
  labels:
    app: dc-mongo-server
  name: dc-mongo-client-service
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 32000
  selector:
    app: dc-mongo-server
  type: LoadBalancer